# Generated by Django 4.2.4 on 2023-09-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_number', models.IntegerField()),
                ('wheel_count', models.IntegerField()),
                ('manufacture', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['lp_number'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.vehicle')),
                ('is_air_conditioned', models.BooleanField()),
                ('has_roof_top', models.BooleanField()),
            ],
            bases=('app.vehicle',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.vehicle')),
                ('max_goods_weight', models.IntegerField()),
            ],
            bases=('app.vehicle',),
        ),
    ]
