# Generated by Django 4.2.5 on 2023-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bike_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['manufacture']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
