# Generated by Django 4.2.5 on 2023-09-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vehicle_options_vehicle_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
    ]
