# Generated by Django 4.2.5 on 2023-09-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_shop_owner_remove_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='file',
        ),
    ]
